version: '2'
services:
 web:
  build: .
  command: bash -c "python manage.py makemigrations && pyhton manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  volumes:
  - .:/to-do
  ports:
  - "8000:8000"
